- search/docs/WFS3core+STAC.yaml
- search/lib/convert/granules.js
- search/scripts/yamlUpdater.js
- search/tests/convert/granules.spec.js
This branch fixes the `datetime` extent for STAC Items in the conversion from Granules to Items. It was a small fix in `lib/convert/granules.js`, as well as the accompanying tests in `test/convert/granules.spec.js`. 
Previously, the temporal extent was returning : 
`datetime: "start_time/end_time"`
Now the temporal extent has three fields:
```
datetime: start_time,
start_datetime: start_time,
end_datetime: end_time 
```
The decision to populate the `datetime` field with the `start_time` was based on the example STAC Item here:
https://github.com/radiantearth/stac-spec/tree/master/extensions/
If the CMR granule being converted doesn't have an `end_time`, the `end_datetime` field is populated with the granule's `start_time`.
> [SCV-13] Datetime Fix

- package-lock.json
- search/docs/WFS3core+STAC.yaml
- search/lib/convert/bounding-box.js
- search/scripts/yamlUpdater.js
- search/tests/convert/bounding-box.spec.js
- search/tests/convert/collections.spec.js
This branch fixes the ordering of the values in the spacial extent conversion. Previously it was returning 
`[min-lon, max-lat, max-lon, min-lat]`
now it returns
`[min-lon, min-lat, max-lon, max-lat]`
This took some minor changes to the `bounding-box.js` conversion file as well as updating tests in `bounding-box.spec.js` and `collections.spec.js`
> [SCV-32] Spacial extent value order

- docs/WFS3core+STAC.yaml
- package-lock.json
- search/lib/convert/granules.js
- search/lib/settings.js
- search/lib/stac/catalog.js
- search/package-lock.json
- search/scripts/yamlUpdater.js
- search/tests/api/stac.spec.js
- search/tests/convert/granules.spec.js
Both required fields `stac_version` and `license` were missing from the collections fields. I added them both to the granules from the yaml doc defining stac data inside of the repo. I also updated the test to expect both fields.
> [SCV-20] Added Missing Collection Fields

- docs/WFS3core+STAC.yaml
- search/lib/api/stac.js
- search/lib/stac/catalog.js
- search/lib/stac/link.js
- search/tests/stac/catalog.spec.js
- search/tests/stac/link.spec.js
This ticket was created due to a bug where links pointing to the next page in a collection were using `rel=child` when they should be using `rel=next`. To fix this I did the following:
Inside of `/lib/stac/link.js` I added key-value pair of `next: 'next'` to RELATION_TYPES`. In addition to that I created a function called `createNext` which follows the same pattern of most of the other functions in the file.
Inside of `/lib/stac/catalog.js` I created an `addNext` function inside of the `Catalog` class which essentially updates an object to `rel: 'next'` and pushes it to the links array.
Inside of `/lib/api/stac.js` I created updated the `forEach` inside of `getCatalog` that looks for any object that includes the word `providers` inside of a link and runs the `addnext` function on that …
> [SCV-21] Update Pagination

- search/lib/stac/link.js
- search/tests/stac/catalog.spec.js
The purpose of this ticket was to have question marks removed from the end of self links. I added a conditional statement inside of `createSelf` that checks to see if the string contains a question mark and if so it removes the last character in that string, where the question mark exists.
> [SCV-24] Question Marks In Self Links

- search/lib/convert/collections.js
- search/tests/convert/collections.spec.js
The issue was, as the title suggests, that the temporal extent for most collections was incorrect. Specifically, the `time_end` field was incorrectly the exact same as the start time. This was due to a line of code in the collections conversion that looked for `time_end` in the CMR collection and set it to `time_start` if it wasn't found. STAC temporal extents must be an array of two datetime strings, which I'm assuming is why the `time_start` was used as the second value.
The fix is a rather minor change–– If `time_end` isn't found, the STAC collection will have `null` as the second value in the temporal extent array as per the STAC spec here:
https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#temporal-extent-object
> [SCV-14] Temporal Extent Incorrect for Most Collections

- search/lib/cmr/index.js
- search/package-lock.json
- search/tests/cmr/cmr.spec.js
This merge has a relatively minor change implemented. Previously, in the conversion from a `/stac/search` query payload to a CMR querystring, the converter was looking for a property called `colleciotnId`. That property was incorrect, and should have been `collections`. This branch makes that change to the STAC search parameter conversion map and associated tests.
> [SCV-30] Invalid Search Param

- search/lib/api/stac.js
- search/lib/validator/index.js
- search/lib/validator/schemaValidator.js
- search/lib/validator/stacValidator.js
- search/package-lock.json
- search/tests/api/stac.spec.js
- search/tests/validator/schemaValidator.spec.js
- search/tests/validator/stacValidator.spec.js
- search/tests/validator/validator.spec.js
These tickets brought together two goals, validate stac items, and return 400 on invalid items. In the past, you could search for invalid collections and providers that didn't exist and get a "bare-bones" stac collection. There was also an issue with features that missed some required data coming in as well.
My solution was to add functions to the validator that would validate stac items. I ultimately ended up splitting the schema validator functions and stac validator functions into two files and exporting them through `index.js` after a suggestion from @DrewE84. I also created a test for the new functions. In addition to this, I responded to invalid stac search items returning `400` responses.
> [SCV-22][SCV-26] Validate STAC

- search/lib/convert/granules.js
- search/tests/convert/granules.spec.js
The issue here was that `browse` types weren't being displayed. I added code to look at file extensions and either return `images/{determinedType}` or `images/jpeg` by default.
> [SCV-25] Browser Types

- search/lib/convert/collections.js
- search/lib/convert/granules.js
- search/serverless-offline.yml
- search/tests/convert/collections.spec.js
- search/tests/convert/granules.spec.js
This branch replaces collection IDs with the more readable and usable `short_name` field, and granule IDs with the `producer_granule_id`. These are implemented in the conversion of CMR granules and collections to STAC collections and items.
> [SCV-27][SCV-28] Replace ID with Short Name

- search/lib/convert/bounding-box.js
- search/lib/convert/collections.js
- search/lib/convert/granules.js
- search/tests/convert/bounding-box.spec.js
- search/tests/convert/collections.spec.js
This branch fixes the spatial extent bug that made its way to UAT. 
Essentially, the ordering of the Bounding Boxes was incorrect after converting a CMR collection to a STAC collection. CMR `boxes` are stored in the order `[minLat, minLon, maxLat, maxLon]`, where STAC `bbox` values are ordered `[minLon, minLat, maxLon, maxLat]`. This was only happening when converting CMR boxes, but not polygons or points.
I added a simple function to `convert/bounding-box.js` called `reorderBoxValues()`. The functionality that was already in the bbox conversion was working well, and could handle merging multiple CMR `boxes` into a single STAC `bbox`. So `reorderBoxValues()` takes that output and reorders it to fit the STAC specifications.
I added tests to both `reorderBoxValues()` and …
> [SCV-55] Spatial Extent for Collections Fixed

- search/lib/convert/granules.js
- search/tests/convert/granules.spec.js
This branch has a quick fix for the image types set for browse images. Previously it was 'images' when MIME standards say it should be 'image'. 
I also did a small refactor of a longer series of if statements to improve readability and performance.
> [SCV-68] MIME Image Label

- search/lib/convert/collections.js
- search/lib/convert/granules.js
- search/tests/convert/collections.spec.js
- search/tests/convert/granules.spec.js
This branch is the fix/update for the UAT 5/20 UAT build in which links in collections and items were broken. 
The issue was that in the branch for the original tickets (SCV-27 and SCV-28), we were trying to surface `short_name` instead of `id`. The motivation to do so was that STAC users typically use the `short_name`, and would be less familiar with the CMR `id`. 
However, when replacing `id` with `short_name` in the links broke them since a `collections/{short_name}` query to CMR results in an error. 
In order to keep the updated IDs and still have functioning links, I reverted the link-builder to use the CMR collection and item IDs while still surfacing `short_name` in the description. 
I would hazard a guess that we're going to have some additional work that relates to this ticket …
> [SCV-75] Fix New Collection and Item IDs (5/20 UAT Build)

- search/lib/convert/collections.js
- search/tests/convert/collections.spec.js
This branch removes the 'proprietary' keyword from the license field. Now, the conversion will look for a `license` field in the CMR collection, and either use this or leave this field as null. This will mean it won't always be STAC compliant, but this was OKed by the client.
> HOTFIX Remove "proprietary" from license in collections

- search/lib/application.js
- search/lib/convert/collections.js
- search/lib/convert/granules.js
- search/tests/convert/collections.spec.js
- search/tests/convert/granules.spec.js
- search/tests/example-data/lancemodis_stac_gran.json
- search/tests/example-data/larc_stac_coll.json
- search/tests/example-data/lpdaac_stac_coll.json
- search/tests/example-data/lpdaac_stac_gran.json
Small fixes to links:
CMR-6859: change 'provider' in collection links to 'parent'
CMR-6860: add link to root catalog in collections
CMR-6861: fix parent link in individual items to point to the collection (/collection/<collectionId>), not the set of items within the collection (/collection/<collectionId>/items)
Updates to corresponding tests and fixture data
> small link fixes (resolves CMR-6859, CMR-6860, CMR-6861)

- search/lib/convert/granules.js
- search/lib/util/index.js
- search/tests/api/wfs.spec.js
This fixes the original CMR-6780 which worked locally but not when deployed. The code was expecting an `httpMethod` field in the event requestContext which was present offline but not when deployed.
> [CMR-6780] pagination

- search/lib/api/wfs.js
When no granules or found, or when limit=0, the response should still be the expected FeatureCollection, but with no features 
numberMatched is still present which is why it's useful to return, because you can make a query, set limit=0, and still see how many hits there were.
> [CMR-7099] return empty response when no granules returned (none found or limit=0)

- search/lib/cmr.js
- search/tests/cmr/cmr.spec.js
Fixes problem in previous PR that updated to use new collection IDs, where an error was thrown if the collection had no granules
> [CMR-6779] return empty facets if no granules

- search/lib/api/wfs.js
- search/lib/cmr.js
- search/tests/cmr/cmr.spec.js
Previous PR #124 added using new Collection IDs of the form `<entry-title>.v<version>` instead of the CMR collection_concept_id, for all endpoints other than /search. 
This PR adds the new collection Ids to /search and updates the convertParam functions to be async.  New collection Ids are translated to collection_concept_id by querying the collection from CMR. A cache is maintained to reduce subsequent calls.
> [CMR-7139] search collectionids

- search/lib/api/provider.js
- search/lib/api/wfs.js
- search/lib/cmr.js
- search/tests/api/provider.spec.js
- search/tests/api/wfs.spec.js
- search/tests/cmr/cmr.spec.js
Missing collections, either in the path parameter `/collections/NoSuchCollection` or when searching `/search?collections[]=NoSuchCollection` will both throw a 404.
Was going to ignore invalid collections when searching at `/search` but on further thought this seemed like arbitrary behavior and would not be clear to a user. If user specifies 2+ collections, you can safely ignore one and only get back matches on the other.
But what if the user provides a single non-existent collection? If ignored, this would return all matching granules across all collections.
It seems better for the user to raise a 404 in both cases.
This PR also cleans up the CMR module and consolidates some functions.
> [CMR-7139] missing collections

- search/lib/api/provider.js
- search/lib/api/stac.js
- search/lib/api/wfs.js
- search/lib/cmr.js
- search/lib/settings.js
- search/lib/util/index.js
- search/serverless.yml
- search/tests/api/provider.spec.js
- search/tests/api/stac.spec.js
- search/tests/api/wfs.spec.js
- search/tests/convert/granules.spec.js
This PR contains several fixes
- errors are no longer thrown when no collections are found for a provider, instead there are just no links from the catalog, and an empty array at the /collections endpoint
- Invalid collections throw error at the /collections/<collectionId> and subsequent endpoints, but collections provided to the `collections` parameter at /search do not throw an error, they just won't return any results for that collection
- `collections` and `ids` can not be provided multiple times in GET requests (CMR-7140)
- provider catalog pagination when more than 10 collections (CMR-7164)...this was set up to work with the /cloudstac endpoint but not /stac. Both now share the same code for fetching collections
> [CMR-7139] fixes to collection ids, pagination, and error responses

- search/lib/api/provider.js
- search/lib/api/wfs.js
- search/tests/api/provider.spec.js
- search/tests/api/wfs.spec.js
This is to fix the pagination next link for CMR-7167. 
Also included fix for CMR-7161: Remove the artificially added query parameter "collections" in page links, in the case of /stac/GHRC_DAAC/collections/lislip.v4/items?limit=1 when <collectionId> appears in the URL.
> CMR-7167: Removed the hardcoded pageSize in getProvider and getCollections

- search/lib/api/wfs.js
- search/lib/util/index.js
- search/tests/api/provider.spec.js
- search/tests/api/stac.spec.js
- search/tests/api/wfs.spec.js
Reverts CMR-7140 since using multiValueQueryStringParameters requires enabling multi-value-headers when using a load balancer (which we are)....and enabling it seems to break all GET requests.
Will have to figure out issue with that prior to adding back in multi-value parameter support.
> revert accepting multiple parameters via GET

- search/package.json
- search/serverless-cloudstac.yml
When deploying both cmr-stac and cmr-cloudstac using the same serverless.yml, there is a conflict that they both try to create the same bucket, which needs to be unique. Created a new serverless-cloudstac.yml that has the same content as serverless.yml but without creating bucket and uploading the docs file. It only needs to be done in one of the deployments.
> CMR-7174: Added a separate serverless-cloudstac.yml 

- mirror-api/mirror-api.py
- mirror-api/requirements.txt
The mirror-api.py script has been updated to use an experimental branch of PySTAC (https://github.com/stac-utils/pystac/tree/mah/async) that allows for async writing of a catalog.
Writing 23K Items + 4K sub-catalogs takes 18 minutes, less than half the time without async.
> [CMR-7209] async s3 writes when mirroring API

- README.md
- package-lock.json
- package.json
- search/package-lock.json
- search/package.json
Changes:
* Upgrade serverless-offline to support nodejs14.x, related issue https://github.com/dherault/serverless-offline/issues/1172 and commit https://github.com/dherault/serverless-offline/commit/ab8ff9de89ba45f1aea23da489d8bfc010d3f59c
* Add some more helpful instruction to the README
> Upgrade serverless and readme

- search/lib/util/index.js
Checks to see if resourcePath is present in context before setting.
This will work in offline and production when a domain name is assigned to the API URL, but an API Gateway deployment with a stage will still have incorrect links. Since there's currently no use case for that this seems an acceptable solution.
> only adjust stagePath if var is present

- search/lib/api/provider.js
- search/tests/api/provider.spec.js
Adds links to `self`, `root`, and `about` to the CMR-STAC root catalog.
The `about` link is the CMR-STAC wiki page https://wiki.earthdata.nasa.gov/display/ED/SpatioTemporal+Asset+Catalog+%2528CMR-STAC%2529+Documentation
> add root links and update tests

- search/lib/api/wfs.js
- search/lib/cmr.js
- search/lib/convert/granules.js
- search/tests/convert/granules.spec.js
- search/tests/example-data/lancemodis_cmr_gran.json
- search/tests/example-data/lpdaac_cloud_gran.json
- search/tests/example-data/lpdaac_stac_gran.json
This changes Item IDs to use the provider `GranuleUR` in the UMM JSON metadata.
Resolves #21
> [CMR-7371] Use GranuleUR for Item IDs

- search/lib/api/provider.js
- search/lib/convert/collections.js
- search/lib/settings.js
- search/lib/util/index.js
- search/package.json
- search/serverless.yml
- search/tests/api/provider.spec.js
- search/tests/api/stac.spec.js
- search/tests/api/wfs.spec.js
- search/tests/convert/collections.spec.js
- search/tests/convert/granules.spec.js
- search/tests/example-data/lancemodis_cloud_gran.json
- search/tests/example-data/lancemodis_stac_gran.json
- search/tests/example-data/larc_cloud_coll.json
- search/tests/example-data/larc_stac_coll.json
- search/tests/example-data/lpdaac_cloud_coll.json
- search/tests/example-data/lpdaac_cloud_gran.json
- search/tests/example-data/lpdaac_stac_coll.json
- search/tests/example-data/lpdaac_stac_gran.json
- search/tests/util/app.spec.js
Rather than getting the protocol (http/https) from the headers, there is an environment variable added, CMR_STAC_PROTOCOL that defaults to `https`.  When running offline with `npm run start` it will use `http`.
In addition, the `trs` and `crs` fields in the Collection `extent` object has been removed in this PR (there is no ticket for this), as those are no longer part of the OGC API Features spec. Only a lat/lon CRS and Gregorian datetime are allowed.
> [CMR-7289] protocol 

- search/lib/cmr.js
- search/lib/util/index.js
This allows `ids` and `collections` to be comma-delimited arrays to be used in GET requests.  See spec: 
https://github.com/radiantearth/stac-api-spec/tree/master/item-search#query-parameters-and-fields
> [CMR-7140] accept comma-delimited strings or arrays for ids and collections

- scripts/validation/requirements.txt
- search/lib/api/provider.js
- search/lib/cmr.js
- search/lib/convert/collections.js
- search/lib/convert/granules.js
- search/tests/convert/granules.spec.js
- search/tests/example-data/lancemodis_cmr_gran.json
- search/tests/example-data/lpdaac_cmr_gran.json
This PR:
- When getting granules it uses fields from the UMM JSON to determine the Collection ID rather than making an extra call to CMR. In the case where the `CollectionReference` in the granule only consists of `EntryTitle` (rather than `ShortName` and `Version`) a call is made to CMR to get the full collection record.
- CMR Collection conversion to STAC uses a standardized function to determine STAC ID
- Invalid versions (given as "Not provided" or "NA") are handled now by omitting version from the STAC ID. A STAC ID for a CMR Collection that does not have a valid version is just the collection `<short_name>` rather than `<short_name>.v<version>`
> [CMR-7370][CMR-7291] Reduce CMR calls to collections, handle invalid collections

- search/lib/cmr.js
- search/tests/cmr/cmr.spec.js
When browsing with temporal facets, such as https://cmr.earthdata.nasa.gov/stac/LPDAAC_ECS/collections/MOD09A1.v061/2000/02/18, the concept ID is used as the stac title. Elsewhere, cmr-stac now uses granule UR for this title, so clicking on these item links returns an internal server error (500). This changes the item links to properly use the granule UR.
> CMR-7622: Use proper stac title for items when searching with temporal facets

- search/package.json
The 'npm start' script (which runs a local sls offline command by default) does not work for local development as is; it needs an extra custom parameter. This small change adds that extra custom parameter, allowing cmr-stac to run locally with the npm start script.
> CMR-8510: add custom parameter to npm start for sls offline local development

- resources/swagger.json
- src/domains/__tests__/items.spec.ts
- src/domains/stac.ts
- src/utils/index.ts
- src/utils/testUtils.ts
This change will adopt the current labeling strategy for download assets, by extracting the key name from the second-to-last index of the href url when split on periods.
Current functionality:
```"assets": {
"download_0": {
"href": "s3://lp-prod-protected/HLSL30.020/HLS.L30.T59WPT.2013101T001445.v2.0/HLS.L30.T59WPT.2013101T001445.v2.0.B09.tif",
"title": "Direct Download [1]",
"description": "This link provides direct download access via S3 to the granule",
"roles": [
"data"
]
},
"download_1": {
"href": "s3://lp-prod-protected/HLSL30.020/HLS.L30.T59WPT.2013101T001445.v2.0/HLS.L30.T59WPT.2013101T001445.v2.0.Fmask.tif",
"title": "Direct Download [1]",
"description": "This link provides direct download access via S3 to the granule",
"roles": [
"data"
]
},      
}
```
New functionality: …
> CMR-9207: Updating key extraction and labeling for download assets

- src/__tests__/providerCatalog.spec.ts
- src/routes/browse.ts
- src/routes/catalog.ts
Use collections instead of data, add a description key, and add missing /stac/ to next page link
> CMR-10038, CMR-10039, and CMR-10040

- .github/workflows/run_tests.yaml
- package-lock.json
- package.json
- src/__tests__/providerCatalog.spec.ts
- src/__tests__/providerCollection.spec.ts
- src/domains/providers.ts
- src/routes/browse.ts
- src/routes/catalog.ts
- src/routes/index.ts
Adding support for collection-search:
-  Adds collection search extension to conformsTo
-  Initially, I considered adding a /collections/search route for searching collections. While this is a valid approach, it's more aligned with STAC browser to implement collection search directly at the /collections level. (see [discussion here](https://github.com/radiantearth/stac-browser/issues/481)).
- A user can now search for collection based on spatial and temporal fields. 
-  In STAC browser there is now a `Search for Collections` tab 
- Collection Search though a `CURL`
- GET: `curl "http://localhost:3000/stac/LPCLOUD/collections?bbox=-180,-90,180,90"`
- POST : ```curl -X POST "http://localhost:3000/stac/PROVIDER_ID/collections" \ -H "Content-Type: application/json" \ -d `{ "bbox": [-180, -90, …
```
> CMR-10151: Add Collection Search Endpoint

- src/__tests__/providerCollection.spec.ts
- src/domains/collections.ts
- src/domains/providers.ts
- src/domains/stac.ts
- src/middleware/index.ts
- src/models/GraphQLModels.ts
- src/models/StacModels.ts
Adds support for free text search functionality for collection search. Users can now search for collections using a query parameter `q` in GET requests or as part of the JSON body in POST requests.
1. Implemented free text search in the `/collections` endpoint
2. Added support for the `q` parameter in both GET and POST requests
3. Modified GraphQL query to include keyword search
GET request: 
```
curl -X GET "http://localhost:3000/stac/PROVIDER/collections?q=MODIS" -H "Accept: application/json"
```
POST request: 
```
curl -X POST "http://localhost:3000/stac/PROVIDER/collections" \
-H "Content-Type: application/json" \
-H "Accept: application/json" \
-d '{
"q": "MODIS",
"limit": 10
}'
```
STAC browser:
> CMR-10163: Implement Free text search for collection search

- src/domains/__tests__/collections.spec.ts
- src/domains/__tests__/items.spec.ts
- src/domains/stac.ts
CMR-STAC users were complaining that the metadata xml file is missing from the assets field in CMR-STAC. Adding this back for them.
> CMR-10128: Adding metadata xml file back to assets

- src/__tests__/providerCatalog.spec.ts
- src/domains/__tests__/collections.spec.ts
- src/domains/__tests__/items.spec.ts
- src/domains/__tests__/stac.spec.ts
- src/domains/collections.ts
- src/domains/items.ts
- src/domains/stac.ts
- src/models/GraphQLModels.ts
- src/routes/catalog.ts
- src/utils/testUtils.ts
This PR addresses two issues:
1. Removes the custom `entryID` generation that was previously based on `shortName` and `version` from the metadata.
2. Fixes a bug in platform processing where null `instruments` fields were causing errors.
- Now using the `entryID` provided directly from CMR instead of constructing it.
- Updated the platform processing logic to handle cases where the `instruments` field is null or undefined.
- Verified that collections are now being returned correctly in the SIT environment.
- Added unit tests to cover cases where `instruments` are null or undefined within platform data.
> CMR-10122: Use EntryId returned by CMR for ID in CMR-STAC

- .github/workflows/lint.yaml
- .github/workflows/run_tests.yaml
- serverless.dev.yml
- serverless.yml
- src/__tests__/providerCatalog.spec.ts
- src/domains/collections.ts
- src/domains/stac.ts
- src/routes/catalog.ts
Adds a reasonable page size of 100 for collection results. Also remove the logic where STAC was getting all of collections for a given provider. This was causing performance issue when a provider had thousands of collections records. Now if a provider have a more than 100 collection, a next link will be provider where they can retrieve next set of results
> CMR-10118: Update default paging functionality for CMR-STAC

- src/__tests__/providerCollection.spec.ts
- src/domains/__tests__/collections.spec.ts
- src/domains/collections.ts
- src/routes/__tests__/browse.spec.ts
- src/routes/browse.ts
The browse route will now only render one link with rel=item.
If the collection has a curator-supplied STAC API it will use that as the link, otherwise it will insert the generic CMR-STAC based one.
Added unit tests for browse.ts (there needs to be a lot more for existing functionality)
> CMR-10221: Fixed double-rendering of items in browse route.

- src/routes/__tests__/browse.spec.ts
- src/routes/browse.ts
The /items path was missing from rel=items links belonging to collections who have granule metadata in CMR. This resolves that problem. Needs to be addressed before the next release to UAT.
> CMR-10242: Fix `/items`/ path for collections which have granule metadata

- package-lock.json
- package.json
- src/domains/__tests__/stac.spec.ts
- src/domains/stac.ts
- src/routes/browse.ts
- src/routes/catalog.ts
- src/routes/items.ts
- src/routes/search.ts
When using cmr-stac and specifying an intersects Point parameter via pystac, cmr-stac responds with an "APIError: {"errors":["Oops! Something has gone wrong. We have been alerted and are working to resolve the problem. Please try your request again later."]}"
What is actually happening is that the initial call is succeeding, but pystac is trying to get all the items, and cmr-stac fails when the next link is called. The next link is specified as follows: http://localhost:3000/stac/LPCLOUD/search?datetime=2024-01-01T00%3A00%3A00Z%2F2024-03-31T23%3A59%3A59Z&collections=HLSS30_2.0&intersects%5Btype%5D=Point&intersects%5Bcoordinates%5D=-105.97%2C35.78&cursor=eyJqc29uIjoiW1wibHBjbG91ZFwiLDE3MDkwNTY0NTAxMzAsMjg4MTI1MDg4OF0iLCJ1bW0iOiJbXCJscGNsb3VkXCIsMTcwOTA1NjQ1MDEzMCwyODgxMjUwODg4XSJ9
The …
> CMR-10200: Fixing stringifyQuery by using qs's version

- src/middleware/__tests__/index.spec.ts
- src/middleware/index.ts
CMR-STAC's validBbox function may be passed an array of strings. In this case, the comparison between points does a comparison with strings. When negative numbers are used, comparing negative numbers as strings doesnt work properly.
Need to cast the comparison as numbers so numerical comparison is used instead of string comparison.(for negative numbers)
When a bbox array of string is passed in.
- **Environment for testing:**
- **Collection to test with:**
Can use the following url to test:
https://cmr.earthdata.nasa.gov/stac/LPCLOUD/search?bbox[0]=-122.09&bbox[1]=39.89&bbox[2]=-122.03&bbox[3]=39.92&datetime=2024-01-01T00:00:00Z/2024-09-24T00:00:00Z&limit=1&collections=HLSL30_2.0
Currently getting an error as follows:
{"errors":["BBOX must be in the form of 'bbox=swLon,swLat,neLon,neLat' …
> CMR-10146: Making sure validBbox compares numbers and not strings

- src/@types/StacCollection.d.ts
- src/__tests__/items.spec.ts
- src/__tests__/providerCatalog.spec.ts
- src/__tests__/providerCollection.spec.ts
- src/__tests__/providerSearch.spec.ts
- src/__tests__/rootCatalog.spec.ts
- src/domains/collections.ts
- src/domains/providers.ts
- src/domains/stac.ts
- src/middleware/index.ts
- src/routes/__tests__/browse.spec.ts
- src/routes/browse.ts
- src/routes/catalog.ts
- src/routes/healthcheck.ts
- src/routes/index.ts
- src/utils/testUtils.ts
Allows users to perform collection searches across all providers.
Add the virtual catalog 'ALL' which will return collection inventories without a provider clause in the collection query
- /stac - adds the 'all' child
- /stac/ALL - returns collections across all providers using each collection's provider to formulate rel=child links.
- /stac/ALL/collections - returns detailed collections across all providers using each collection's provider to formulate 
- rel=item links.
- /stac/ALL/search - disallowed
- **SIT**
- **Any collection**
1. Navigate to cmr.sit.earthdata.nasa.gov/stac
2. Observe child link 
`{
"rel": "child",
"title": "all",
"type": "application/json",
"href": "https://cmr.sit.earthdata.nasa.gov/stac/ALL"
}`
3. Navigate to cmr.sit.earthdata.nasa.gov/stac/ALL
4. Observe absence …
> CMR-10238: Adding the virtual catalog 'ALL'

- src/__tests__/providerSearch.spec.ts
- src/app.ts
Currently, the default array limit of the qs parser in express is set to 20. When arrays with more than 20 items are passed to CMR STAC as query parameters(for coodinates of an intersects parameter), array indices are added. The CMR STAC code cannot handle the array indices so it errors out.
Increasing the array limit of the default qs parser in express to 100. This will allow coordinates of up to 100 points.
CMR STAC
You can try the following on a browser locally or in PROD with the proper URL:
https://cmr.earthdata.nasa.gov/stac/LPCLOUD/search?datetime=2024-01-01T00:00:00Z/2024-01-31T23:59:59Z&collections[0]=HLSS30_2.0&intersects[type]=Polygon&intersects[coordinates][0][0][0]=-48.31876570764564&intersects[coordinates][0][0][1]=-24.13235588091331&intersects[coordinates][0][1][0]=-48.31918 …
> CMR-10296: Adding arrayLimit to qs parser to increase the array limit without indices
