- docs/WFS3core+STAC.yaml
- search/lib/convert/granules.js
- search/scripts/yamlUpdater.js
I added a collection field to items with `rel=collection` and a link to the collection.
> SCV-16] Add Collection Field in Items

- docs/WFS3core+STAC.yaml
- search/lib/convert/granules.js
- search/lib/settings.js
- search/lib/stac/catalog.js
- search/tests/api/stac.spec.js
- search/tests/convert/granules.spec.js
> Revert "[SCV-20] Added Missing Collection Fields"

- docs/WFS3core+STAC.yaml
- search/lib/convert/granules.js
- search/scripts/yamlUpdater.js
> Revert "SCV-16] Add Collection Field in Items"

- docs/deleteLater.md
> [SCV-16] Collection Field In Items

- docs/deleteLater2.md
> [SCV-20] Missing collection Fields

- docs/WFS3core+STAC.yaml
- search/lib/convert/granules.js
- search/scripts/yamlUpdater.js
I added a bbox field to items from with a value of `cmrGran.boxes`, `stac_version` was already addressed in an earlier ticket.
> [CSV-19] Bbox In Items

- search/lib/convert/granules.js
- search/tests/convert/granules.spec.js
Made an update adding the collection field with the collection Id.
> [SCV-16] Added collection field with the collectionID.

- search/lib/convert/granules.js
- search/tests/convert/granules.spec.js
Providers were being displayed in properties when they should have been displayed in links. I moved field and updated test around it.
> [SCV-31] Move Provider to Links

- search/serverless-offline.yml
This branch adds in the line Cayvon suggested for the local deployment using the serverless-offline.yml
> [SCV-11] Local Deploy Fix.

- LICENSE.txt
- README.md
This branch updates the README.md in the root directory of the project.
- Updated recommended node.js version to 10.15 (as specified in the .nvmrc)
- Changed `Deployed At` link to reflect current CMR deployment link
- Changed software License.txt
> [SCV-39] Update README

- search/lib/convert/collections.js
- search/lib/convert/granules.js
- search/tests/convert/collections.spec.js
- search/tests/convert/granules.spec.js
> Revert "[SCV-27][SCV-28] Replace ID with Short Name"

- search/lib/application.js
- search/package-lock.json
- search/package.json
- search/tests/api/extensions/query.spec.js
add CORS support using CORS middleware with Express
> [CMR-6776] CORS support

- search/lib/api/provider.js
- search/tests/api/extensions/query.spec.js
- search/tests/api/provider.spec.js
- Refactors landing page to be a STAC compliant catalog
- update tests
> [CMR-6781] redo landing page

- README.md
- search/lib/api/stac.js
- search/tests/api/extensions/query.spec.js
- search/tests/api/stac.spec.js
- Fixes POST body getting ignored
- Restores missing README contents
- resolve linter warning in test
> [CMR-6749] fix post

- README.md
- search/lib/api/provider.js
- search/lib/application.js
- search/lib/settings.js
- search/serverless-offline.yml
- search/serverless.yml
- search/tests/api/extensions/extension.spec.js
- search/tests/api/provider.spec.js
- search/tests/api/stac.spec.js
- search/tests/api/wfs.spec.js
- search/tests/application.spec.js
- search/tests/convert/collections.spec.js
- search/tests/convert/granules.spec.js
- search/tests/example-data/lancemodis_stac_gran.json
- search/tests/example-data/larc_stac_coll.json
- search/tests/example-data/lpdaac_stac_coll.json
- search/tests/example-data/lpdaac_stac_gran.json
- search/tests/stac/catalog.spec.js
- search/tests/util/app.spec.js
Rewrite URL middleware to allow changing the root URL in deployed environments.
> CMR-6676 URL Rewrite Middleware

- .eslintrc
- package.json
- search/lib/api/stac.js
- search/lib/api/wfs.js
- search/lib/cmr.js
- search/lib/convert/collections.js
- search/lib/convert/granules.js
- search/lib/stac/catalog.js
- search/serverless-offline.yml
- search/serverless.yml
- search/tests/api/provider.spec.js
- search/tests/api/stac.spec.js
- search/tests/api/wfs.spec.js
- search/tests/cmr/cmr.spec.js
- search/tests/convert/collections.spec.js
- search/tests/convert/granules.spec.js
- search/tests/stac/catalog.spec.js
- search/tests/util.js
- search/tests/util/app.spec.js
Work applied on top of #103 
Additionally applied linting and best practices
> CMR-6857 CMR-6864 PR Continued

- search/package.json
Upgraded ajv from 6.5.1 to 6.12.3 in /search
> CMR-6983: Upgraded ajv from 6.5.1 to 6.12.3

- search/package-lock.json
* The lockfile is used by snyk for scanning - the lockfile needs to be committed for the high vulnerabilities to show as resolved on the snyk dashboard.
> CMR-6982 + CMR-6983: Committing lockfile for snyk scanning purposes

- search/lib/api/stac.js
- search/lib/api/wfs.js
- search/lib/cmr.js
- search/lib/convert/collections.js
- search/lib/convert/granules.js
- search/lib/util/index.js
- search/serverless.yml
- search/tests/api/stac.spec.js
- search/tests/api/wfs.spec.js
- search/tests/cmr/cmr.spec.js
- search/tests/convert/collections.spec.js
- search/tests/convert/granules.spec.js
- search/tests/example-data/larc_stac_coll.json
- search/tests/example-data/lpdaac_cmr_gran_umm.json
- search/tests/example-data/lpdaac_stac_coll.json
- search/tests/util.js
resolves:
CMR-6993
CMR-6994
CMR-6995
CMR-6997
CMR-6858
> [CMR-6993] et al - cleanup and misc fixes

- search/lib/api/provider.js
- search/lib/util/app.js
- search/tests/api/provider.spec.js
- Adds conformsTo links to provider catalogs
- updates search link `type` field to `application/geo+json`
- adds `method` field to provider search link with value of 'GET'
- adds additional provider search link with method=POST
> Update API conformance

- search/lib/util/index.js
Fixed link generation when using serverless offline to run locally
> [CMR-7387] fix path generation when stage is in base URL

- search/lib/api/wfs.js
- search/lib/cmr.js
- search/package-lock.json
- search/package.json
- search/tests/cmr/cmr.spec.js
- search/tests/convert/granules.spec.js
- search/tests/util.js
> [CMR-7206][CMR-7415] bounding box and search content-type

- README.md
- docs/usage.md
Adds additional documentation (and used to update EOSDIS wiki)
> [CMR-7434] Additional documentation

- adr-log/adr-00000000-template.md
- adr-log/adr-20190926-initial-design.md
- adr-log/adr-20221201-graphql-backend.md
- adr-log/adr-20230323-entry-id-title-identifiers.md
- src/domains/__tests__/stac.spec.ts
- src/domains/stac.ts
- src/routes/search.ts
- src/utils/__tests__/utils.spec.ts
- src/utils/index.ts
Fixes a case where a single collection would not have the IDs properly converted.
Adds architectural decision logs.
> CMR-8991 fixes collections conversion

- docs/README.md
See [CMR-9057](https://bugs.earthdata.nasa.gov/browse/CMR-9057) and the previous [PR](https://github.com/nasa/cmr-stac/pull/294) for more details
> CMR-9057-2: Fixing README.md Reference Path

- package-lock.json
- package.json
> CMR-9527 Snyk vulnerabilities
